export default ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';

export default ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';

export default ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export default CLEAR_ERRORS = 'CLEAR_ERRORS';